import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { lazy, Suspense } from "react";

const SceneComponent = lazy(() => import("../components/Scene"));

const Home: NextPage = (props: any) => {
  return (
    <div>
      <Head>
        <title>Introspection</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Suspense fallback={"Loading . . ."}>
        <SceneComponent props={props} />
      </Suspense>
    </div>
  );
};

export default Home;

export async function getStaticProps() {
  return {
    props: {
      devMode:
        process.env.NODE_ENV === "development" ||
        process.env.VERCEL_ENV === "preview",
    },
  };
}
