import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Scene from "../components/Scene";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Introspection</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Scene></Scene>
    </div>
  );
};

export default Home;
